FROM flink:1.18

USER root

# install python for pyflink
RUN apt-get update && apt-get install -y python3 python3-pip \
    && ln -s /usr/bin/python3 /usr/bin/python

# copy connector jars into flink classpath
COPY flink/lib/flink-sql-connector-kafka-3.1.0-1.18.jar /opt/flink/lib/
COPY flink/lib/iceberg-flink-runtime-1.18-1.9.2.jar /opt/flink/lib/

USER flink